name: jarvis_core
description: Advanced 3D Holographic AI Assistant OS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  shared_preferences: ^2.3.2
  http: ^1.2.0

flutter:
  uses-material-design: true
